config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :companies, only: [:index, :show, :new, :create, :edit, :update]
  resources :vehicles, only: [:index, :new, :create, :edit, :update]
  resources :prices, only: [:index, :new, :create, :edit, :update]
  resources :deadlines, only: [:index, :new, :create, :edit, :update]
  resources :quotations, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show] do
    get 'search', on: :collection
    post 'accepted', on: :member
    post 'refused', on: :member
    post 'delivered', on: :member
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :company
  enum status: {pending: 0, accepted: 5, refused: 10, delivered: 15}
  
  before_validation :generate_tracking_code, on: :create

  validates :recipient_name, :recipient_registration_number, :recipient_telephone, 
            :recipient_email, :recipient_address, :recipient_postal_code, :recipient_city, :recipient_state,
            :product_code, :product_length, :product_height, :product_width, :product_weight, :address, 
            :postal_code, :city, :state, :tracking_code, presence: true
  validates :recipient_registration_number, format: {with: /\A\d{3}\.?\d{3}\.?\d{3}\-?\d{2}\Z/}
  validates :recipient_telephone, format: {with: /\A\(?\d{2}\)?\d{4,5}\-?\d{4}\Z/}
  validates :recipient_email, format: {with: /\A[^@\s]+@[^@\s]+\z/}
  validates :postal_code, format: {with: /\A\d{2}\.?\d{3}\-?\d{3}\Z/}
  validates :recipient_postal_code, format: {with: /\A\d{2}\.?\d{3}\-?\d{3}\Z/}

  def delivery_address
    "#{recipient_address} - #{recipient_city} - #{recipient_state}"
  end

  def full_address
    "#{address} - #{city} - #{state}"
  end

  def dimensions
    "#{product_length} cm x #{product_width} cm x #{product_height} cm"
  end

  private

  def generate_tracking_code
    self.tracking_code = SecureRandom.alphanumeric(15).upcase
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: [:search]
  before_action :set_order_and_check_user, only: [:accepted, :refused, :delivered]

  def new
   @order = Order.new
   @companies = Company.all
  end

  def create
    order_params = params.require(:order).permit(:company_id, :recipient_name, :recipient_registration_number, :recipient_telephone,
                                                 :recipient_email, :recipient_address, :recipient_postal_code, :recipient_city, 
                                                 :recipient_state, :product_code, :product_length, :product_height, :product_width, 
                                                 :product_weight, :address, :postal_code, :city, :state)
    @order = Order.new(order_params)
  
   if @order.save()
     redirect_to @order, notice:'Ordem de serviço registrada com sucesso.'
    else
      @companies = Company.all
      flash.now[:alert]='Não foi possível gerar a ordem de serviço.'
      render 'new'
    end
  end
  
  def show
    @order = Order.find(params[:id])
  end

  def search
    @tracking_code = params['query']
    @order = Order.find_by(tracking_code: @tracking_code)
  end

  def accepted
    @order.accepted!
    redirect_to @order
  end

  def refused
    @order.refused!
    redirect_to @order
  end

  def delivered
    @order.delivered!
    redirect_to @order
  end

  private

  def set_order_and_check_user
    @order = Order.find(params[:id])
    if @order.company != current_user.company
      return redirect_to root_path
    end
  end
end

app/views/orders/new.html.erb
<h1>Criar <%= Order.model_name.human %></h1>

<% if (@order.errors.any?) %> 
    <p>Verifique os erros abaixo:</p>
    <ul>
        <%@order.errors.full_messages.each do |msg| %>
            <li><%= msg %>.</li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @order) do |f|%>
  <div>
    <%= f.label :recipient_name %>
    <%= f.text_field :recipient_name %>
  </div>
  <div>
    <%= f.label :recipient_registration_number %>
    <%= f.text_field :recipient_registration_number %>
  </div>
  <div>
    <%= f.label :recipient_telephone %>
    <%= f.text_field :recipient_telephone %>
  </div>
  <div>
    <%= f.label :recipient_email %>
    <%= f.text_field :recipient_email %>
  </div>
  <div>
    <%= f.label :recipient_address %>
    <%= f.text_field :recipient_address %>
  </div>
  <div>
    <%= f.label :recipient_postal_code %>
    <%= f.text_field :recipient_postal_code %>
  </div>
  <div>
    <%= f.label :recipient_city %>
    <%= f.text_field :recipient_city %>
  </div>
  <div>
    <%= f.label :recipient_state %>
    <%= f.text_field :recipient_state %>
  </div>
  <div>
    <%= f.label :product_code %>
    <%= f.text_field :product_code %>
  </div>
  <div>
    <%= f.label :product_length %>
    <%= f.number_field :product_length %> cm
  </div>
  <div>
    <%= f.label :product_height %>
    <%= f.number_field :product_height %> cm
  </div>
  <div>
    <%= f.label :product_width %>
    <%= f.number_field :product_width %> cm
  </div>
  <div>
    <%= f.label :product_weight %> 
    <%= f.number_field :product_weight %> g
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :company_id %>
    <%= f.collection_select :company_id, @companies, :id, :full_description %>
  </div>
  
  <%= f.submit 'Gerar Ordem de Serviço' %>
<% end %>

app/views/orders/search.html.erb
<h1>Resultado da Busca por: <%= @tracking_code %></h1>

<% if @order.present? %>
  <dl>
    <dt><strong><%= Order.human_attribute_name(:tracking_code) %>: </strong></dt>
    <dd><%= @order.tracking_code %></dd>
    <dt><strong><%= Order.human_attribute_name(:recipient_name) %>: </strong></dt>
    <dd><%= @order.recipient_name %></dd>
    <dt><strong><%= Order.human_attribute_name(:product_code) %>: </strong></dt>
    <dd><%= @order.product_code %></dd>
  </dl>
<% else %>
  <p>Não foi possível encontrar o pedido.</p>
<% end %>

app/views/orders/show.html.erb
<h2><%= Order.model_name.human %></h2>

<h3><%= Order.human_attribute_name(:company_id) %>: <%= @order.company.full_description %></h3>
<h3><%= Order.human_attribute_name(:tracking_code) %>: <%= @order.tracking_code %></h3>
<h3><%= Order.human_attribute_name(:status) %>: <%= I18n.t(@order.status) %></h3>
  
<section>
  <h4>DADOS DO DESTINATÁRIO</h4>
  <dl>
    <dt><strong><%= Order.human_attribute_name(:recipient_name) %>: </strong></dt>
    <dd><%= @order.recipient_name %></dd>
    <dt><strong><%= Order.human_attribute_name(:recipient_registration_number) %>: </strong></dt>
    <dd><%= @order.recipient_registration_number %></dd>
    <dt><strong><%= Order.human_attribute_name(:recipient_telephone) %>: </strong></dt>
    <dd><%= @order.recipient_telephone %></dd>
    <dt><strong><%= Order.human_attribute_name(:recipient_email) %>: </strong></dt>
    <dd><%= @order.recipient_email %></dd>
    <dt><strong><%= Order.human_attribute_name(:recipient_address) %>: </strong></dt>
    <dd><%= @order.delivery_address %></dd>
    <dt><strong><%= Order.human_attribute_name(:recipient_postal_code) %>: </strong></dt>
    <dd><%= @order.recipient_postal_code %></dd>
  </dl>
</section>

<section>
  <h4>DADOS DO PRODUTO</h4>
  <dl>
    <dt><strong><%= Order.human_attribute_name(:product_code) %>: </strong></dt>
    <dd><%= @order.product_code %></dd>
    <dt><strong>Dimensões do Produto: </strong></dt>
    <dd><%= @order.dimensions %></dd>
    <dt><strong><%= Order.human_attribute_name(:product_weight) %>: </strong></dt>
    <dd><%= @order.product_weight %> g</dd>
    <dt><strong><%= Order.human_attribute_name(:address) %>: </strong></dt>
    <dd><%= @order.full_address %></dd>
    <dt><strong><%= Order.human_attribute_name(:postal_code) %>: </strong></dt>
    <dd><%= @order.postal_code %></dd>
  </dl>
</section>

<% if @order.pending? %>
  <%= button_to 'Aceitar Ordem de Serviço', accepted_order_path(@order.id) %>
  <%= button_to 'Recusar Ordem de Serviço', refused_order_path(@order.id) %>
<% elsif @order.accepted? %>
  <%= button_to 'Pedido Entregue', delivered_order_path(@order.id) %>
<% end %>