config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :companies, only: [:index, :show, :new, :create, :edit, :update]
  resources :vehicles, only: [:index, :new, :create, :edit, :update]
  resources :prices, only: [:index, :new, :create, :edit, :update]
  resources :deadlines, only: [:index, :new, :create, :edit, :update]
  resources :quotations, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show] do
    get 'search', on: :collection
    post 'accepted', on: :member
    post 'refused', on: :member
    post 'delivered', on: :member
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :deadlines
  has_many :prices
  has_many :vehicles

  validates :brand_name, :corporate_name, :domain, :registration_number, :postal_code, 
            :billing_address, :city, :state, :domain, presence: true
  validates :registration_number, :domain, uniqueness: true
  validates :postal_code, format: {with: /\A\d{2}\.?\d{3}\-?\d{3}\Z/}
  validates :registration_number, format: {with: /\A\d{2}\.?\d{3}\.?\d{3}\/?\d{4}\-?\d{2}\Z/}
  validates :domain, format: {with: /\A@[^@\s]+\z/}

  def full_description
    "#{brand_name} | #{corporate_name} | #{state}"
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user! 
  before_action do 
    redirect_to root_path unless current_user.admin
  end
  before_action :set_company, only: [:show, :edit, :update]

  def index
    @companies = Company.all.order(:brand_name)
  end

  def show; end

  def new
    @company = Company.new
  end

  def create
    company_params
    @company = Company.new(company_params)

    if @company.save()
      redirect_to @company, notice:'Transportadora cadastrada com sucesso.'
    else
      flash.now[:alert]='Transportadora não cadastrada.'
      render 'new'
    end
  end

  def edit; end

  def update
    company_params
    if @company.update(company_params)
      redirect_to company_path(@company.id), notice: 'Transportadora atualizada com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar a transportadora.'
      render 'edit'
    end                                      
  end

  private

    def set_company
        @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:corporate_name, :brand_name, :domain, :city, :registration_number, 
                                      :postal_code, :billing_address, :city, :state)
    end
end

app/views/companies/_form.html.erb
<%=form_with(model: @company) do |c|%>
  <div>
    <%= c.label :brand_name %>
    <%= c.text_field :brand_name %>
  </div>
  <div>
    <%= c.label :registration_number %>
    <%= c.text_field :registration_number %>
  </div>
  <div>
    <%= c.label :corporate_name %>
    <%= c.text_field :corporate_name %>
  </div>
  <div>
    <%= c.label :postal_code %>
    <%= c.text_field :postal_code %>
  <div>
  <div>
    <%= c.label :state %>
    <%= c.text_field :state %>
  </div>
  <div>
    <%= c.label :city %>
    <%= c.text_field :city %>
  </div>
  <div>
    <%= c.label :billing_address %>
    <%= c.text_field :billing_address %>
  <div>
    <%= c.label :domain %>
    <%= c.text_field :domain %>
  </div>
  <div>
    <%= c.submit 'Enviar' %>
  </div>
<%end%>

app/views/companies/edit.html.erb
<h2>Editar <%= Company.model_name.human %></h2>

<%= render 'form'%>

app/views/companies/index.html.erb
<h2>Transportadoras Ativas</h2>

  <nav><%=link_to 'Cadastrar Transportadora', new_company_path%></nav>

  <%@companies.each do |c|%>
    <% if c.domain != '@sistemadefrete.com.br'%>
    <div>
      <h3><%= link_to c.brand_name, c%> - <%= c.state %></h3>
    </div>
    <% end %>
  <% end %>

  <%if @companies.count == 1 && @companies[0].domain == '@sistemadefrete.com.br' %>
    <p>Não existem transportadoras ativas.</p>
  <%end%>

app/views/companies/new.html.erb
<h2>Cadastrar <%= Company.model_name.human %></h2>

<% if (@company.errors.any?) %> 
    <p>Verifique os erros abaixo:</p>
    <ul>
        <%@company.errors.full_messages.each do |msg| %>
            <li><%= msg %>.</li>
        <% end %>
    </ul>
<% end %>

<%= render 'form' %>

app/views/companies/show.html.erb
<h2><%= @company.brand_name.upcase %></h2>

<section>
  <h3>DADOS CADASTRAIS</h3>
  <dl>
    <dt><strong><%= Company.human_attribute_name(:registration_number).upcase %>: </strong></dt>
    <dd><%= @company.registration_number %></dd>
    <dt><strong><%= Company.human_attribute_name(:corporate_name).upcase %>: </strong></dt>
    <dd><%= @company.corporate_name.upcase %></dd>
  </dl>
</section>

<section>
  <h3>LOCALIZAÇÃO</h3>
  <dl>
    <dt><strong><%= Company.human_attribute_name(:billing_address).upcase %>: </strong></dt>
    <dd><%= @company.billing_address.upcase %></dd>
    <dt><strong>CIDADE | ESTADO: </strong></dt>
    <dd><%= @company.city.upcase %> | <%= @company.state %></dd>
    <dt><strong><%= Company.human_attribute_name(:postal_code).upcase %>: </strong></dt>
    <dd><%= @company.postal_code %></dd>
  </dl>
</section>

<section>
  <h3><%= Company.human_attribute_name(:domain).upcase %></h3>
  <p><%= @company.domain%></p>
</section>

<div>
  <%= link_to('Editar', edit_company_path(@company)) %>
</div>

<div>
  <%= link_to('Voltar', companies_path) %>
</div>