config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :companies, only: [:index, :show, :new, :create, :edit, :update]
  resources :vehicles, only: [:index, :new, :create, :edit, :update]
  resources :prices, only: [:index, :new, :create, :edit, :update]
  resources :deadlines, only: [:index, :new, :create, :edit, :update]
  resources :quotations, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show] do
    get 'search', on: :collection
    post 'accepted', on: :member
    post 'refused', on: :member
    post 'delivered', on: :member
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :license_plate, :v_model, :v_brand, :v_year, :max_load, presence: true
  validates :license_plate, uniqueness: true
  validates :license_plate, format: {with: /\A[A-Z]{3}\d{1}[A-Z0-9]{1}\d{2}\Z/}

  belongs_to :company
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicle_and_check_user, only: [:edit, :update]

  def index
    @vehicles = current_user.company.vehicles
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    vehicle_params
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.company = current_user.company

    if @vehicle.save()
      redirect_to vehicles_path, notice:'Veículo cadastrado com sucesso.'
    else
      flash.now[:alert]='Veículo não cadastrado.'
      render 'new'
    end
  end

  def edit; end

  def update
    vehicle_params
    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path, notice: 'Veículo atualizado com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar o veículo.'
      render 'edit'
    end                                      
  end

  private

    def set_vehicle_and_check_user
        @vehicle = Vehicle.find(params[:id])
        if @vehicle.company != current_user.company
          return redirect_to root_path
        end
    end

    def vehicle_params
      params.require(:vehicle).permit(:license_plate, :v_brand, :v_model, :v_year, :max_load)
    end
end

app/views/vehicles/_form.html.erb
<%= form_with(model: @vehicle) do |v| %>
  <div>
    <%= v.label :v_brand %>
    <%= v.text_field :v_brand %>
  </div>
  <div>
    <%= v.label :v_model %>
    <%= v.text_field :v_model %>
  </div>
  <div>
    <%= v.label :v_year %>
    <%= v.number_field :v_year %>
  </div>
  <div>
    <%= v.label :max_load %>
    <%= v.number_field :max_load %> kg
  <div>
  <div>
    <%= v.label :license_plate %>
    <%= v.text_field :license_plate %>
  </div>
  <div>
    <%= v.submit 'Enviar' %>
  </div>
<%end%>

app/views/vehicles/edit.html.erb
<h2>Editar <%= Vehicle.model_name.human %></h2>

<%= render 'form'%>

app/views/vehicles/index.html.erb
<h2>Veículos Ativos</h2>

<nav><%= link_to 'Cadastrar Veículo', new_vehicle_path %></nav>

<% if @vehicles.any? %>
  <table>
    <thead>
      <tr>
        <th><%= Vehicle.human_attribute_name(:v_brand) %></th>
        <th><%= Vehicle.human_attribute_name(:v_model) %></th>
        <th><%= Vehicle.human_attribute_name(:v_year) %></th>
        <th><%= Vehicle.human_attribute_name(:max_load) %></th>
        <th><%= Vehicle.human_attribute_name(:license_plate) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @vehicles.each do |v| %>
        <tr>
          <td><%= v.v_brand %></td>
          <td><%= v.v_model %></td>
          <td><%= v.v_year %></td>
          <td><%= v.max_load %> kg</td>
          <td><%= v.license_plate %></td>
          <td><%= link_to('Editar', edit_vehicle_path(v))%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem veículos ativos.</p>
<% end %>
  



app/views/vehicles/new.html.erb
<h2>Criar <%= Vehicle.model_name.human %></h2>

<%if (@vehicle.errors.any?)%> 
    <p>Verifique os erros abaixo:</p>
    <ul>
        <%@vehicle.errors.full_messages.each do |msg|%>
            <li><%=msg%>.</li>
        <%end%>
    </ul>
<%end%>

<%= render 'form'%>