config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :companies, only: [:index, :show, :new, :create, :edit, :update]
  resources :vehicles, only: [:index, :new, :create, :edit, :update]
  resources :prices, only: [:index, :new, :create, :edit, :update]
  resources :deadlines, only: [:index, :new, :create, :edit, :update]
  resources :quotations, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show] do
    get 'search', on: :collection
    post 'accepted', on: :member
    post 'refused', on: :member
    post 'delivered', on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Entregas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do%>
        <h1>Sistema de Entregas</h1>
      <% end %>
      <nav>
        <% if user_signed_in? %>
          <%= current_user.description %>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
            <% if current_user.admin? %>
              <%= link_to 'Transportadoras', companies_path %> |
              <%= link_to 'Criar Ordem de Serviço', new_order_path %> |
              <%= link_to 'Criar Orçamento', new_quotation_path %> |
            <% else %>
              <p><%= current_user.company.full_description %></p>
              <%= link_to 'Preços', prices_path %> |
              <%= link_to 'Prazos', deadlines_path %> |
              <%= link_to 'Veículos', vehicles_path %> |
            <% end %>
        <% else %>
           <%= link_to 'Entrar como Empresa', new_user_session_path%> |
        <% end %>
      </nav>
    </header>
    <main>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
  </body>
</html>